### ISSUE TITLE
Linux .desktop file

### ISSUE THREAD

**Issue by Shatur** [Skycoder42/QTaskbarControl#1]
Thanks for your awesome library!
I suggest to use [desktopFileName](https://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop) from QGuiApplication instead of setting it manually in via `setAttribute`. It will allow to call `QGuiApplication::setDesktopFileName("myapp.desktop")` in `main.cpp` only once for all classes.

**Comment by Skycoder42** [comment]
Thats a good idea - I did not know of this property until now!

**Comment by Shatur** [comment]
Great! I can send a pull request for it if you busy now.

**Comment by Skycoder42** [comment]
That would be awesome! Simply remove `SetupKey::LinuxDesktopFile` enum value and change the code to use the GUI applications value, I will tag this as a new major version. Also, do not forget to update the README.
